global using SpotifyAPI.Web;
global using Microsoft.Extensions.Configuration;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using static SpotifyAPI.Web.Scopes;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Text;
global using Newtonsoft.Json;